random-xs:
  faiss_HNSW_Optimized:
    module: benchmark_anns.bench.algorithms.faiss_HNSW_Optimized.faiss_HNSW_Optimized
    constructor: FaissHnswOptimized
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [{"efConstruction": 120, "indexkey": "HNSWOptimized16", "gorder_window": 5, "apply_gorder": true}]
        query-args: |
          [{"ef": 40}]

sift:
  faiss_HNSW_Optimized:
    module: benchmark_anns.bench.algorithms.faiss_HNSW_Optimized.faiss_HNSW_Optimized
    constructor: FaissHnswOptimized
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [
          # {"efConstruction": 40, "indexkey": "HNSWOptimized16", "gorder_window": 5, "apply_gorder": true},
          # # {"efConstruction": 40, "indexkey": "HNSWOptimized32", "gorder_window": 5, "apply_gorder": true}, 
          # # {"efConstruction": 40, "indexkey": "HNSWOptimized64", "gorder_window": 5, "apply_gorder": true}, 
          # # {"efConstruction": 40, "indexkey": "HNSWOptimized32", "gorder_window": 3, "apply_gorder": true}, 
          # # {"efConstruction": 40, "indexkey": "HNSWOptimized32", "gorder_window": 7, "apply_gorder": true}, 
          {"efConstruction": 120, "indexkey": "HNSWOptimized16", "apply_gorder": false}
          ]
        query-args: |
          [
          {"ef": 40}
          # {"ef": 32}, 
          # {"ef": 64},
          # {"ef": 128}
          ]
